doctrine:
    dbal:
        types:
            organizer_id: App\Organization\Infrastructure\Persistence\Doctrine\Type\OrganizerIdType
            organization_id: App\Organization\Infrastructure\Persistence\Doctrine\Type\OrganizationIdType
            checkout_session_id: App\Organization\Infrastructure\Persistence\Doctrine\Type\CheckoutSessionIdType
            checkout_reference: App\Organization\Infrastructure\Persistence\Doctrine\Type\CheckoutReferenceType
    orm:
        mappings:
            Organization:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Organization/Infrastructure/Persistence/Doctrine/mapping'
                prefix: 'App\Organization\Domain\Model'
                alias: Organization