services:
    App\Competition\Domain\Repository\CompetitionRepository: '@App\Competition\Infrastructure\Persistence\InMemory\InMemoryCompetitionRepository'
    App\Organization\Domain\Repository\OrganizerRepository: '@App\Organization\Infrastructure\Persistence\InMemory\InMemoryOrganizerRepository'
